renderHeader({title:'Fila de Moderação',subtitleHtml:'Jogos <span style="color: var(--amber-400);">Submetidos</span>'}); renderFooterNav('moderacao');
document.getElementById('preview-title-icon').innerHTML=`${ICONS.gamepad} Preview do Jogo`; document.getElementById('acoes-title-icon').innerHTML=`${ICONS.shield} Ações de Moderação`; document.getElementById('btn-aprovar').innerHTML=`${ICONS.checkCircle} Aprovar`; document.getElementById('btn-reprovar').innerHTML=`${ICONS.xCircle} Reprovar`;
const motivosWrap=document.getElementById('motivos-selects'); const motivos=['Conteúdo inadequado','Problema técnico','game.json inválido','Problema de direitos autorais']; motivosWrap.innerHTML=motivos.map((m,i)=>`<select id="motivo-${i}"><option value="">${m}</option><option value="${m}">${m}</option></select>`).join('');
let indice=0,decisao=null;
function carregar(){const j=FILA_MODERACAO[indice]; if(!j)return; document.getElementById('mod-cover').src=j.capa||'';document.getElementById('mod-preview-img').src=j.capa||'';document.getElementById('mod-titulo').textContent=j.titulo||j.nome;document.getElementById('mod-autores').textContent=j.autor||j.autores?.join(', ');document.getElementById('mod-enviado').textContent=j.enviadoEm||'-';document.getElementById('mod-descricao').textContent=j.descricao||j.resumo||''; decisao=null; document.getElementById('reject-fields').classList.remove('is-visible'); atualizar(); renderPag();}
function atualizar(){const b=document.getElementById('btn-confirmar'); b.disabled=!decisao || (decisao==='reprovar'&&!Array.from(motivosWrap.querySelectorAll('select')).some(s=>s.value)); b.textContent=decisao==='aprovar'?'Aprovar Jogo':decisao==='reprovar'?'Reprovar Jogo':'Registrar Decisão';}
document.getElementById('btn-aprovar').onclick=()=>{decisao='aprovar';document.getElementById('reject-fields').classList.remove('is-visible');atualizar();}; document.getElementById('btn-reprovar').onclick=()=>{decisao='reprovar';document.getElementById('reject-fields').classList.add('is-visible');atualizar();}; motivosWrap.onchange=atualizar;
document.getElementById('btn-confirmar').onclick=async()=>{const j=FILA_MODERACAO[indice]; const justificativa=Array.from(motivosWrap.querySelectorAll('select')).map(s=>s.value).filter(Boolean).join('; '); const r=await fetch(`${API_BASE_URL}/jogos/${j.id}/decisao`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({decisao:decisao==='aprovar'?'aprovado':'reprovado',justificativa,moderador:'G2'})}); const ok=r.ok; document.getElementById('confirmacao-icone').innerHTML=ok?ICONS.checkCircle:ICONS.xCircle; document.getElementById('confirmacao-texto').textContent=ok?'Decisão registrada com sucesso!':`Erro ao registrar decisão: ${(await r.json()).erro||'API indisponível'}`; openModal('modal-confirmacao');};
function renderPag(){const p=document.getElementById('pagination');p.innerHTML=FILA_MODERACAO.map((_,i)=>`<button class="${i===indice?'is-active':''}" data-i="${i}">${i+1}</button>`).join('');p.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{indice=Number(b.dataset.i);carregar();});}
API_DATA_READY.then(carregar);
